// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybwwphviyavqvuucizdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlid3dwaHZpeWF2cXZ1dWNpemRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NDI0NzIsImV4cCI6MjA1NzAxODQ3Mn0.DCrpYfXouDKlopb_GPoXtqreljnBst-kimREE80kUpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);